export const initialItemValues = {
  text1: null,
  text2: null,
  text3: null,
  checkbox1: null,
  checkbox2: null,
  checkbox3: null,
  number1: null,
  number2: null,
  number3: null,
  date1: null,
  date2: null,
  date3: null,
  textarea1: null,
  textarea2: null,
  textarea3: null,
};
