export const topicsRu = [
  { value: "Книги", label: "Книги" },
  { value: "Мебель", label: "Мебель" },
  { value: "Электроника", label: "Электроника" },
  { value: "Валюта", label: "Валюта" },
  { value: "Карты", label: "Карты" },
  { value: "Игрушки", label: "Игрушки" },
  { value: "Марки", label: "Марки" },
  { value: "Напитки", label: "Напитки" },
  { value: "Искусство", label: "Искусство" },
  { value: "Плакаты ", label: "Плакаты" },
  { value: "Фигурки", label: "Фигурки" },
  { value: "Автографы", label: "Автографы" },
  { value: "Банки", label: "Банки" },
  { value: "Бутылки", label: "Бутылки" },
  { value: "Другой", label: "Другой" },
];

export const topicsEng = [
  { value: "Books", label: "Books" },
  { value: "Furniture", label: "Furniture" },
  { value: "Electronics", label: "Electronics" },
  { value: "Currency", label: "Currency" },
  { value: "Cards", label: "Cards" },
  { value: "Toys", label: "Toys" },
  { value: "Stamps", label: "Stamps" },
  { value: "Drinks", label: "Drinks" },
  { value: "Art ", label: "Jewelry" },
  { value: "Posters ", label: "Posters" },
  { value: "Action Figures", label: "Action Figures" },
  { value: "Autographs", label: "Autographs" },
  { value: "Cans", label: "Cans" },
  { value: "Bottles", label: "Bottles" },
  { value: "Other", label: "Other" },
];
